services:
  catalogue:
    build: ./catalogue
    image: esrasd/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    build: ./user
    image: esrasd/user:1.0.0
    container_name: user
    depends_on:
    - redis
  cart:
    build: ./cart
    image: esrasd/cart:1.0.0
    container_name: cart
    depends_on:
    - redis
  mysql:
    build: ./mysql
    image: esrasd/mysql:1.0.0
    container_name: mysql
    
  frontend:
    build: ./frontend
    image: esrasd/frontend:1.0.0
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
    - mongodb
    - catalogue
    - redis
    - user
    - cart
    
  mongodb:
    build: ./mongodb # it movies to mongodb directory
    image: esrasd/mongodb:1.0.0 # docker build -t esrasd/mongodb:1.0.0
    container_name: mongodb
  redis:
    image: redis:7.0
    container_name: redis
networks:
  default:
    driver: bridge
    name: roboshop
    external: false #if true, you need to create network manually